.Dd June 26, 2026
.Dt LIBVHDI 3
.Os
.Sh NAME
.Nm libvhdi.h
.Nd Library to access the Virtual Hard Disk (VHD) image format
.Sh SYNOPSIS
.In libvhdi.h
.Pp
Support functions
.nf
.Ft const char *
.Fo libvhdi_get_version
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_get_access_flags_read
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_get_access_flags_read_write
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_get_access_flags_write
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_get_codepage
.Fa "int *codepage"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_set_codepage
.Fa "int codepage"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_check_file_signature
.Fa "const char *filename"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.Pp
Available when compiled with wide character string support:
.nf
.Ft int
.Fo libvhdi_check_file_signature_wide
.Fa "const wchar_t *filename"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libvhdi_check_file_signature_file_io_handle
.Fa "libbfio_handle_t *file_io_handle"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.Pp
Notify functions
.nf
.Ft void
.Fo libvhdi_notify_set_verbose
.Fa "int verbose"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_notify_set_stream
.Fa "FILE *stream"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_notify_stream_open
.Fa "const char *filename"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_notify_stream_close
.Fa "libvhdi_error_t **error"
.Fc
.fi
.Pp
Error functions
.nf
.Ft void
.Fo libvhdi_error_free
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_error_fprint
.Fa "libvhdi_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_error_sprint
.Fa "libvhdi_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_error_backtrace_fprint
.Fa "libvhdi_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_error_backtrace_sprint
.Fa "libvhdi_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.Pp
File functions
.nf
.Ft int
.Fo libvhdi_file_initialize
.Fa "libvhdi_file_t **file"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_free
.Fa "libvhdi_file_t **file"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_signal_abort
.Fa "libvhdi_file_t *file"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_open
.Fa "libvhdi_file_t *file"
.Fa "const char *filename"
.Fa "int access_flags"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_close
.Fa "libvhdi_file_t *file"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libvhdi_file_read_buffer
.Fa "libvhdi_file_t *file"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libvhdi_file_read_buffer_at_offset
.Fa "libvhdi_file_t *file"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "off64_t offset"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft off64_t
.Fo libvhdi_file_seek_offset
.Fa "libvhdi_file_t *file"
.Fa "off64_t offset"
.Fa "int whence"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_offset
.Fa "libvhdi_file_t *file"
.Fa "off64_t *offset"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_set_parent_file
.Fa "libvhdi_file_t *file"
.Fa "libvhdi_file_t *parent_file"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.Pp
Available when compiled with wide character string support:
.nf
.Ft int
.Fo libvhdi_file_open_wide
.Fa "libvhdi_file_t *file"
.Fa "const wchar_t *filename"
.Fa "int access_flags"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libvhdi_file_open_file_io_handle
.Fa "libvhdi_file_t *file"
.Fa "libbfio_handle_t *file_io_handle"
.Fa "int access_flags"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.Pp
Meta data functions
.nf
.Ft int
.Fo libvhdi_file_get_file_type
.Fa "libvhdi_file_t *file"
.Fa "int *file_type"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_format_version
.Fa "libvhdi_file_t *file"
.Fa "uint16_t *major_version"
.Fa "uint16_t *minor_version"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_disk_type
.Fa "libvhdi_file_t *file"
.Fa "uint32_t *disk_type"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_media_size
.Fa "libvhdi_file_t *file"
.Fa "size64_t *media_size"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_bytes_per_sector
.Fa "libvhdi_file_t *file"
.Fa "uint32_t *bytes_per_sector"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_identifier
.Fa "libvhdi_file_t *file"
.Fa "uint8_t *guid_data"
.Fa "size_t guid_data_size"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_parent_identifier
.Fa "libvhdi_file_t *file"
.Fa "uint8_t *guid_data"
.Fa "size_t guid_data_size"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_utf8_parent_filename_size
.Fa "libvhdi_file_t *file"
.Fa "size_t *utf8_string_size"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_utf8_parent_filename
.Fa "libvhdi_file_t *file"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_utf16_parent_filename_size
.Fa "libvhdi_file_t *file"
.Fa "size_t *utf16_string_size"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libvhdi_file_get_utf16_parent_filename
.Fa "libvhdi_file_t *file"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libvhdi_error_t **error"
.Fc
.fi
.Sh DESCRIPTION
The
.Fn libvhdi_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or \-1 on error, dependent on the return \
type.
For the actual return values see
.In libvhdi.h .
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh NOTES
libvhdi can be compiled with wide character support (wchar_t).
.sp
To compile libvhdi with wide character support use:
.Ar ./configure --enable-wide-character-type
 or define:
.Ar _UNICODE
 or
.Ar UNICODE
 during compilation.
.sp
.Ar LIBVHDI_WIDE_CHARACTER_TYPE
 in libvhdi/features.h can be used to determine if libvhdi was compiled with \
wide character support.
.Sh SEE ALSO
.In libvhdi.h
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libvhdi/issues
.Sh COPYRIGHT
Copyright (C) 2012-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
