= Virtual Hard Disk version 2 (VHDX) image format
Analysis of the VHDX format

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

A commonly image format used in Microsoft virtualization products is the Virtual
Hard Disk version 2 (VHDX) Image format. This specification is based on
available documentation and was enhanced by analyzing test data.

This document is intended as a working document of the data format specification
for the libvhdi project.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Virtual Hard Disk version 2 (VHDX) Image format
| Classification: | Public
| Keywords: | Virtual Hard Disk, VHDX, Virtual PC, Virtual Server, Hyper-V Server
|===

[preface]
== License

....
Copyright (C) 2020, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | October 2020 | Initial version
| 0.0.2 | J.B. Metz | December 2020 | Additional information
|===

:numbered:
== Overview

A commonly image format used in Microsoft virtualization products is the
Virtual Hard Disk version 2 (VHDX) Image format. This specification is
based on available documentation and was enhanced by analyzing test images.

A VHDX image file consist of the following distinguishable elements:

* file (type) identifier
* 2x image headers
* 2x region tables
* log or metadata journal
* block allocation table (BAT) region
* metadata region
** metadata table
** metadata items
* image (content) data

The elements are stored in 64 KiB (65536 bytes) aligned blocks

[yellow-background]*TODO: determine if the header with the largest sequence number was written the latest?*

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | big-endian
| Character strings | Unicode strings are stored in UTF-16 litte-endian without the byte order mark (BOM).
|===

=== Test versions

The following versions of programs were used to generate test data to that was
used for the information in this document:

* Diskpart on Windows 10 (2004)

== File (type) identifier

The file (type) identifier is 64 KiB (65536 bytes) of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | "vhdxfile" | Signature
| 8 | 512 | | Creator application and version +
UTF-16 little-endian string with end-of-string character
| 520 | 65016 | | [yellow-background]*Unknown (reserved)*
|===

== Image header

The image header is 4 KiB (4096 bytes) of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "head" | Signature
| 4 | 4 | | Checksum +
Contains a CRC-32C, which uses the Castagnoli polynomial (0x1edc6f41) of the 4 KiB image header where the checksum value is set to 0
| 8 | 8 | | Sequence number
| 16 | 16 | | [yellow-background]*Unknown (file write identifier)* +
Contains a GUID
| 32 | 16 | | [yellow-background]*Unknown (data write identifier)* +
Contains a GUID
| 48 | 16 | | [yellow-background]*Unknown (log identifier)* +
Contains a GUID
| 64 | 2 | | Log format version
| 66 | 2 | 1 | Format version
| 68 | 4 | | [yellow-background]*Unknown (log size)* +
According to `[MS-VHDX]` this value must be a multitude of 1 MiB
| 72 | 8 | | [yellow-background]*Unknown (log offset)* +
According to `[MS-VHDX]` this value must be a multitude of 1 MiB and greater than or equal to 1 MiB
| 80 | 4016 | 0 | [yellow-background]*Unknown (reserved)* +
According to `[MS-VHDX]` this value must be set to 0
|===

== Region table

The region table is stored in a block of 64 KiB (65536 bytes) and consists of:

* region table header
* 0 or more region table entries
* [yellow-background]*Unknown (reserved)*

[yellow-background]*TODO: determine if 0 entries is actually supported*

=== Region table header

The region table header is 16 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "regi" | Signature
| 4 | 4 | | Checksum +
Contains a CRC-32C, which uses the Castagnoli polynomial (0x1edc6f41) of the 64 KiB region table where the checksum value is set to 0
| 8 | 4 | | Number of table entries +
According to `[MS-VHDX]` this value must be less than or equal to 2047
| 12 | 4 | 0 | [yellow-background]*Unknown (reserved)* +
According to `[MS-VHDX]` this value must be set to 0
|===

=== Region table entry

The region table entry is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | Region type identifier +
Contains a GUID +
See section: <<region_type_identifiers,Region type identifiers>>
| 16 | 8 | | Region data offset +
Contains an offset relative to the start of the file +
According to `[MS-VHDX]` this value must be a multitude of 1 MiB and greater than or equal to 1 MiB
| 24 | 4 | | Region data size +
According to `[MS-VHDX]` this value must be a multitude of 1 MiB
| 28 | 4 | | Is required flag +
Contains 1 to indicate the region is required to be supported by the implementation
|===

=== [[region_type_identifiers]]Region type identifiers

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 2dc27766-f623-4200-9d64-115e9bfd4a08 | | Block allocation table (BAT) region
| 8b7ca206-4790-4b9a-b8fe-575f050f886e | | Metadata region
|===

== Metadata region

The metadata region contains:

* metadata table
* metadata items

=== Metadata table

The metadata table is stored in a block of 64 KiB (65536 bytes) and consists of:

* metadata table header
* 0 or more metadata table entries
* [yellow-background]*Unknown (reserved)*

[yellow-background]*TODO: determine if 0 entries is actually supported*

==== Metadata table header

The metadata table header is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | "metadata" | Signature
| 8 | 2 | 0 | [yellow-background]*Unknown (reserved)* +
According to `[MS-VHDX]` this value must be set to 0
| 10 | 2 | | Number of table entries +
According to `[MS-VHDX]` this value must be less than or equal to 2047
| 12 | 20 | 0 | [yellow-background]*Unknown (reserved)* +
According to `[MS-VHDX]` this value must be set to 0
|===

==== Metadata table entry

The metdata table entry is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | Metadata item identifier +
Contains a GUID +
See section: <<metdata_item_identifiers,Metadata item identifiers>>
| 16 | 4 | | Metadata item offset +
Contains an offset relative to the start of the metadata region +
According to `[MS-VHDX]` this value must be greater than 64 KiB
| 20 | 4 | | Metadata item size
| 24 | 8 | | [yellow-background]*Unknown*
|===

[yellow-background]*TODO: describe last 8 bytes*

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | IsUser |
| 0x00000002 | IsVirtualDisk |
| 0x00000004 | IsRequired |
|===

=== Metadata items

==== [[metdata_item_identifiers]]Metadata item identifiers

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 2fa54224-cd1b-4876-b211-5dbed83bf4b8 | | Virtual disk size
| 8141bf1d-a96f-4709-ba47-f233a8faab5f | | Logical sector size
| a8d35f2d-b30b-454d-abf7-d3d84834ab0c | | Parent locator
| beca12ab-b2e6-4523-93ef-c309e000c746 | | Virtual disk identifier
| caa16737-fa36-4d43-b3b6-33f0aa44e76b | | File parameters
| cda348c7-445d-4471-9cc9-e9885251c556 | | Physical sector size
|===

==== File parameters metadata item

The file parameters metadata item is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Block size +
According to `[MS-VHDX]` this value must be a power of 2 and greater than or equal to 1 MiB and not greater than 256 MiB
| 4.0 | 1 bit | | Blocks remain allocated +
This flag is used to indicate the file is a fixed-size image
| 4.1 | 1 bit | | Has parent +
Value that indicates if the VHDX file contains a differential image that has a parent
| 4.2 | 30 bits | 0 | [yellow-background]*Unknown (reserved)* +
According to `[MS-VHDX]` this value must be set to 0
|===

==== Logical sector size metadata item

The logical sector size metadata item is 4 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Logical sector size +
According to `[MS-VHDX]` this value must be either 512 or 4096
|===

==== Parent locator metadata item

The parent locator metadata item is variable of size and consits of:

* parent locator header
* 0 or more parent locator entry
* parent locator key and value data

[yellow-background]*TODO: determine if 0 entries is actually supported*

===== Parent locator header

The parent locator header is 20 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | Parent locator type indicator +
Contains the GUID: b04aefb7-d19e-4a81-b789-25b8e9445913
| 16 | 2 | 0 | [yellow-background]*Unknown (reserved)* +
According to `[MS-VHDX]` this value must be set to 0
| 18 | 2 | | Number of entries (or key-value pairs)
|===

===== Parent locator entry

The parent locator entry is 12 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Key data offset +
Contains the offset relative from the start of the parent locator header
| 4 | 4 | | Value data offset +
Contains the offset relative from the start of the parent locator header
| 8 | 2 | | Key data size
| 10 | 2 | | Value data size
|===

===== Parent locator key and value data

A parent locator key or value is stored as UTF-16 little-endian string without
end-of-string character.

Known keys are:

[cols="1,5",options="header"]
|===
| Value | Description
| absolute_win32_path | The value contains an absolute drive Windows path "\\?\c:\file.vhdx"
| parent_linkage | The value contains a string of a GUID +
This GUID should correspond to the data write identifier of the parent file
| parent_linkage2 | The value contains a string of a GUID
| relative_path | The value contains a relative Windows path "..\file.vhdx"
| volume_path | The value contains an absolute volume Windows path with "\\?\Volume{%GUID%}\file.vhdx"
|===

==== Physical sector size metadata item

The physical sector size metadata item is 4 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Physical sector size +
According to `[MS-VHDX]` this value must be either 512 or 4096
|===

==== Virtual disk identifier metadata item

The virtual disk identifier metadata item is 16 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | Virtual disk identifier +
Contains a GUID
|===

[NOTE]
In contrast to VHD (version 1) the virtual disk identifier does not change
between a differential image and its parent. The data write identifier seems
to be used instead.

==== Virtual disk size metadata item

The virtual disk size metadata item is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Virtual disk size
|===

== Block allocation table (BAT) region

The block allocation table (BAT) region contains the block allocation table.
The entries of this table describe the location of either blocks containing
image content data (or payload blocks) or blocks containing a sector bitmap.

The size of an individual sector bitmap block is 1 MiB which allows for `2^23`
sectors to be represented by the bitmap.

Block allocation table (BAT) entries are grouped in chunks. The size of a chunk
can be calculated as following:

....
number of entries per chunk = ( 2^23 * logical sector size ) / block size
....

The block allocation table (BAT) consists of:

* one or more chunks containing:
  * number of entries per chunk x BAT entry describing image content data
  * 1 x BAT entry describing the a sector bitmap

Unused BAT entries are filled with 0-byte values.

The block allocation table (BAT) of:

* a fixed-size image does not contain sector bitmap entries;
* a dynamic-size image does contain sector bitmap entries, although according to `[MS-VHDX]` are not used;
* a differential image does contain sector bitmap entries.

=== Block allocation table (BAT) entry

The block allocation table (BAT) entry is 64 bits of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0.0 | 3 bits | | Block state
| 0.3 | 17 bits | 0 | [yellow-background]*Unknown (reserved)* +
According to `[MS-VHDX]` this value must be set to 0
| 2.4 | 44 bits | | Block offset +
Contains the offset relative from the start of the file as a multitude of 1 MiB
|===

=== Block states

==== Payload block states

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | PAYLOAD_BLOCK_NOT_PRESENT | Block is new and therefore not (yet) stored in the file
| 1 | PAYLOAD_BLOCK_UNDEFINED | Block is not stored in the file
| 2 | PAYLOAD_BLOCK_ZERO | Block is sparse and therefore filled with 0-byte values
| 3 | PAYLOAD_BLOCK_UNMAPPED | Block has been unmapped
3+|
| 6 | PAYLOAD_BLOCK_FULLY_PRESENT | Block is stored in the file
| 7 | PAYLOAD_BLOCK_PARTIALLY_PRESENT | Block is stored in the parent
|===

==== Sector bitmap block states

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | SB_BLOCK_NOT_PRESENT | Block is new and therefore not (yet) stored in the file
3+|
| 6 | SB_BLOCK_PRESENT | Block is stored in the file
|===

=== Sector bitmap

In differential disk images the sector bitmap indicates which sectors are stored
within the image (bit set to 1) or in the parent (bit set to 0).

The bitmap is stored in a 1 MiB block.

The bitmap is stored on a per-byte basis with the LSB represents the first bit
in the bitmap.

== Log (metadata journal)

[yellow-background]*TODO: complete this section*

The log serves as metadata journal and consist of a variable-sized contiguous
circular (ring) buffer that contains log entries.

=== Log entry

[yellow-background]*TODO: complete this section*

4 KiB (4096 bytes) in size

==== Log entry header

[yellow-background]*TODO: complete this section*

==== Zero descriptor

[yellow-background]*TODO: complete this section*

==== Data descriptor

[yellow-background]*TODO: complete this section*

==== Data sector

[yellow-background]*TODO: complete this section*

:numbered!:
[appendix]
== References

`[MS-VHDX]`

[cols="1,5",options="header"]
|===
| Title: | Virtual Hard Disk v2 (VHDX) File Format
| Author(s): | Microsoft
| Version: | 4.0
| Date: | September 12, 2018
| URL: | https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-vhdx/83e061f8-f6e2-4de1-91bd-5d518a43d477
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

